# config/s3.yml
development:
  access_key_id: AKIAIWX7LOMXTBZBZHHA
  secret_access_key: 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
  bucket: com.softbadminton

production:
  access_key_id: AKIAIWX7LOMXTBZBZHHA
  secret_access_key: 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
  bucket: com.softbadminton